Fix CI offenses (#1)

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -1,66 +1,72 @@
 ---
-  name: Go CI/CD Pipeline
+name: Go CI/CD Pipeline
 
-  "on":
-    push:
-      branches:
-        - main
-    pull_request:
-    # Allows you to run this workflow manually from the Actions tab
-    workflow_dispatch:
+"on":
+  push:
+    branches:
+      - main
+  pull_request:
+  # Allows you to run this workflow manually from the Actions tab
+  workflow_dispatch:
 
-  jobs:
-    editorconfig:
-      runs-on: ubuntu-latest
-      steps:
-        - uses: actions/checkout@v4
-        - uses: editorconfig-checker/action-editorconfig-checker@main
-        - run: editorconfig-checker
+jobs:
+  editorconfig:
+    runs-on: ubuntu-latest
+    steps:
+      - uses: actions/checkout@v4
+      - uses: editorconfig-checker/action-editorconfig-checker@main
+      - run: editorconfig-checker
 
-    markdown-lint:
-      runs-on: ubuntu-latest
-      steps:
-        - name: Checkout repository
-          uses: actions/checkout@v4
-        - uses: DavidAnson/markdownlint-cli2-action@v16
-          with:
-            globs: '**/*.md'
+  markdown-lint:
+    runs-on: ubuntu-latest
+    steps:
+      - name: Checkout repository
+        uses: actions/checkout@v4
+      - uses: DavidAnson/markdownlint-cli2-action@v16
+        with:
+          globs: '**/*.md'
 
-    yaml-lint:
-      runs-on: ubuntu-latest
-      steps:
-        - name: Checkout repository
-          uses: actions/checkout@v4
+  yaml-lint:
+    runs-on: ubuntu-latest
+    steps:
+      - name: Checkout repository
+        uses: actions/checkout@v4
 
-        - name: Set up Python
-          uses: actions/setup-python@v5
-          with:
-            python-version: '3.x'
+      - name: Set up Python
+        uses: actions/setup-python@v5
+        with:
+          python-version: '3.x'
 
-        - name: Install yamllint
-          run: pip install yamllint
+      - name: Install yamllint
+        run: pip install yamllint
 
-        - name: Run yamllint
-          run: yamllint .
+      - name: Run yamllint
+        run: yamllint .
 
-    spellcheck:
-      runs-on: ubuntu-latest
-      timeout-minutes: 30
-      steps:
-        - name: Checkout
-          uses: actions/checkout@v4
+  spellcheck:
+    runs-on: ubuntu-latest
+    timeout-minutes: 30
+    steps:
+      - name: Checkout
+        uses: actions/checkout@v4
 
-        - name: Install codespell
-          run: pip install codespell
+      - name: Install codespell
+        run: pip install codespell
 
-        - name: Spellcheck
-          # Ignore a CI failure because there are false positives.
-          run: codespell || echo 'Fix misspells via "codespell" on your console, or ignore false positives.'
+      - name: Spellcheck
+        # Ignore a CI failure because there are false positives.
+        run: codespell || echo 'Fix misspells via "codespell"'
 
-
-    stylelint:
-      runs-on: ubuntu-latest
-      steps:
-        - name: Checkout
-          uses: actions/checkout@v4
-        - uses: actions-hub/stylelint@master
+  stylelint:
+    runs-on: ubuntu-latest
+    steps:
+      - name: Checkout
+        uses: actions/checkout@v4
+      - name: Install Node.js
+        uses: actions/setup-node@v3
+        with:
+          node-version: '20' # Specify the Node.js version
+      - name: Install dependencies
+        run: npm install
+      - name: Run CSS lint
+        run: npm run lint:css
